config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: "users/registrations"}
  get "/index", to:"articles#index"
  get '/show',  to:"articles#show"
  get '/new',   to:"articles#new"
  get '/edit',  to:"articles#edit"
  get "/inform", to:"articles#inform"
  root "articles#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body,  presence: true

  attachment :image

  def self.search(search)
    if search
      Article.where(['title LIKE ?', "%#{search}%"])
    else
      Article.all
    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :name, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_many :articles, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_article, only:[:show, :edit, :update, :destroy]
  before_action :validate_user, only:[:show, :edit, :update, :destroy]

  def index
    @article =current_user.articles.order(created_at: :desc).page(params[:page]).per(6).search(params[:search])
    # 検索機能のsearch(params[:search])はページネーションの後ろにつけてok
  end

  def show
    @article =Article.find(params[:id])
  end

  def new
    @article =Article.new
  end

  def edit
  end

  def create
    @article =Article.new(article_params)
    @article.user_id =current_user.id
    if @article.save
      redirect_to @article, notice:"作成できました"
    else
      render :new, alert:"作成できませんでした"
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice:"更新しました"
    else
      render :edit, alert:"更新できませんでした"
    end
  end

  def destroy
    if @article.destroy
      redirect_to root_path, notice:"破棄しました"
    else
      redirect_to root_path, alert:"破棄できませんでした"
    end
  end


  private

  def find_article
    @article =Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :image)
  end

  def validate_user
    if @article.user !=current_user
      redirect_to root_path, alert:"他所の覗き見はできません"
    end
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
     super
     if resource
       profile =Profile.new
       profile.user_id =resource.id
       profile.name =params[:profile][:name]
       profile.save
     end
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= javascript_include_tag 'application' %>
<%= form_for(@article) do |f| %>
  <div id="cover-photo" class="relative">
    <%= f.attachment_field :image %>
    <i class="fa fa-camera"></i>
  </div>

  <div class="form-group">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div>
    <%= f.label :body, "投稿本文" %>
    <%= f.text_area :body, rows:10, class:"form-control" %>
  </div>
  <%= f.submit class:"btn btn-success" %>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
  <div>
    <h1 style="text-align:center;">ブログの編集</h1>
    <%= image_tag "book1.jpg" %>
    <div class="padding-bottom-35">
    </div>
    <%= render "form", article: @article %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
  <% @article.each do |a| %>
    <%= link_to a do %>
    <div class="col-md-4">
      <% if a.image_id.present? %>
        <%= image_tag attachment_url(a, :image), class:"img-responsive-top-15" %>
      <% else %>
        <%= image_tag "book1.jpg" %>
      <% end %>
      <p><%= a.title %></p>
      <%= a.created_at.strftime("%Y/%m/%d") %>
    </div>
    <% end %>
  <% end %><!--<div class="col-md-4">の外で始まるから、その外で終わるべき-->
  </div>
  <%= link_to "新規作成", new_article_path,  class:"btn btn-primary", style:"margin-bottom:10px; margin-top:10px;"  %>
  <%= paginate @article %>
</div>

app/views/articles/inform.html.erb
<h1 style="text-align:center;">概要・お問い合わせ</h1>

<p>こちらへどうぞ</p>
<br>
<br>
<h1 style="text-align:center; font-weight:bold;">ただいま工事中</h1>

app/views/articles/new.html.erb
<div class="container">
  <div>
    <h1 style="text-align:center;">ブログの新規作成</h1>

    <div class="padding-bottom-35">
    <%= render "form" %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div>
    <% if @article.image_id.present? %>
      <%= image_tag attachment_url(@article, :image), class:"article-image padding-15" %>
    <% end %>
    <div class="col-md-4">
      <p><%= @article.title %></p>
      <%= @article.created_at.strftime("%Y/%m/%d") %>
      <p><%= simple_format @article.body %></p>
    </div>
    <%= link_to "編集", edit_article_path(@article), class:"btn btn-primary",
     style:"margin-bottom:10px;" %>
    <%= link_to "削除", article_path(@article), method: :delete,
    data:{confirm:"削除する?"}, class:"btn btn-danger",
    style:"margin-bottom:10px; margin-right:10px;" %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
        <a class="navbar-brand" href="/"><%= current_user.profile.name %>のブログ</a>
      <% else %>
        <a class="navbar-brand" href="/">ブログサービス</a>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="navigation">
      <p class="navbar-text navbar-right">
        <% if user_signed_in? %>
          <%= link_to "新規作成", new_article_path %>
          &nbsp;
        　<%= link_to "ログアウト", destroy_user_session_path, method: :delete  %>
        <% else %>
          <%= link_to "ユーザー登録", new_user_registration_path %>
          &nbsp;
          <%= link_to "ログイン", new_user_session_path %>
      </p>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Blog2App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: "all", 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:whitesmoke;">

    <!-- 新規登録やログイン時にメッセージ表示-->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= form_tag articles_path, method: "get" do %>
      <p>
        <%= text_field_tag :search, params[:search], style:"margin-left:20px; width:300px; height:30px;" %>
        <%= submit_tag "検索", name: nil, class:"btn btn-secondary" %>
      </p>
    <% end %>

    <%= render "layouts/header" %>

    <%= yield %>
    
    <hr>
    <footer>
      <div style="font-size:32px; float:left; margin-left:40px;">ブログサービス</div>
      <div class="footer-list" style="float:right;">
        <ul class="footer-list" style="list-style:none;">
          <li><%= link_to "概要", inform_path %></li>
          <li><%= link_to "お問い合わせ", inform_path %></li>
        </ul>
      </div>
    </footer>
  </body>
</html>